### ISSUE TITLE
カレンダーの配列作成

### ISSUE THREAD

**Issue by azain4645** [azain4645/thanksHabit#1]
https://github.com/azain4645/thanksHabit/blob/828d47834a92235cf0ce4897bc9ddb29699a5bfa/pages/calender.vue#L21-L37

startDateとendDateは、それぞれその月に表示する元の日曜日、土曜日を表しています。
2022年7月であれば、2022/6/26 2022/8/6　になります。

この値を元に、表示する日付を動的に配列として作りたいのですが、うまく動作しません。
7日分startDayから１日づつ足した値✖︎週数の配列にしたいのですが、
date.plus({days: 1})
が機能していないようです。

このdateはstartDateから
let date = startDate.value
のようにコピーして持ってこようとしているのですが、このあたりのやり方に問題があるのでしょうか

**Comment by Kenpal-ShigeruHyodo** [comment]
@azain4645 
おはようございます！ 　上記ですが、luxon はイミュータブルな操作がベースとなっているライブラリですので、基本的にどの操作も、代入しない限りは、元のオブジェクトの不変性が保たれるものと考えてください！

ということですので、上記はこのように書くと機能します。

```diff
       weekRow.push({
         date: date.day,
       });
-      date.plus({days: 1})
+      date = date.plus({days: 1})
     }
     calendars.push(weekRow)
   }
```

このミュータブルか、イミュータブルかというところは大きくて、一昔前は Moment.js のような操作元のオブジェクトの状態が操作ごとに変わっていくスタイル（つまりミュータブル、可変性のある）ライブラリが多かったのですが、次第に「状態は悪」「可変性は悪」という考え方に界隈が移行していきました。

その結果、元々がミュータブルな設計のMoment.js は「え、今更ミュータブルは嫌だとか言われてももう仕様変えられないし...」と自らの限界を悟り、「ミュータブルな自分みたいなライブラリは今の世の中についていけないから、今度から不変性が保証されている後継ライブラリ使ってね」というスタンスを取るようになりました。

その「不変性が保証されている後継ライブラリ」の一つが、luxonというわけです。ですので、luxon と moment のソースコードを比較するときは、 moment のように 「何らかの操作で操作元の値が変わる」ことは基本的にないものと考えて、コードを読んでみてください！
