### ISSUE TITLE
日毎のカウント数を表示したい

### ISSUE THREAD

**Issue by azain4645** [azain4645/thanksHabit#3]
https://github.com/azain4645/thanksHabit/blob/fa18d569ef22a74210dffceca582cfccd9a4133c/pages/calender.vue#L92-L102

すみません、javascriptの基礎的な部分かもしれません。

日毎のカウントデータからその日のデータを取得するところまでは出来ました。
表示するところを
day.count.count
day.count['count']
day[count].count
など試しましたが、エラーとなって白紙になるためうまく表示できません。
連想配列の連想配列の取得の仕方かもしれませんが教えてもらえますか？

**Comment by Kenpal-ShigeruHyodo** [comment]
@azain4645 
お疲れ様です！　遅くなりました。
まずネストした連想配列の取り方からご紹介しますね！

```typescript
// こんなオブジェクトがあるとしたら、
const day = { count: { count: 10 } };

// 「10」を取得するには、こんな風に書ける
day.count.count
day["count"]["count"]
day["count"].count
day.count["count"]

// ちなみにこれは無理です（この時カッコの中は文字列にしないといけない）
// この場合countは文字列ではなく、変数とみなされてしまいます
// day[count][count]
```

実際のコードの方では何が誤りになってるのかも、今見てみますね！

**Comment by Kenpal-ShigeruHyodo** [comment]
@azain4645 
お、そもそものところで「count」という名前のプロパティは、記載いただいたコードの箇所では格納されてませんね！

こんな感じで中身見てみました（dayをJSON化して画面で直接見えるようにした次第です）

```diff
         {{ day.date }}
         {{ day.count }}
+        {{ JSON.stringify(day) }}
       </div>
     </div>
```
<img width="651" alt="スクリーンショット 2022-08-01 19 04 04" src="https://user-images.githubusercontent.com/102776107/182125021-d600988c-8645-4d19-b19d-f45783a60789.png">

なので実際に、 `{{ day.count.count }}` という形で count にアクセスしようとしても、いわゆる NullPointerException  的なものが出てエラーになってしまいますね！

```
TypeError: Cannot read properties of undefined (reading 'count')
```

そういうわけで、これを正常に動かすには、まずは day.count が undefined である状態を解決しないとですね！（どこかで値の連携に失敗してるロジックがあるのではないかと思っています）

**Comment by azain4645** [comment]
![image](https://user-images.githubusercontent.com/47071916/182145845-f33c377c-cecb-41bc-b6e6-c6fe5589cbb3.png)

すみません、コードがプッシュできてなかったかもしれません。今見たらところcount要素自体は入っているようなんですが。。

**Comment by gel1123** [comment]
@azain4645 
おはようございます！　お、そうでしたか。確かに今しがたpullしてみると、一部のカレンダーには count ありますね！
であればあとは、その count を画面に表示するのみです。

> エラーとなって白紙になるためうまく表示できません。

とのことでしたが、その時ターミナルにでているエラー内容はおそらく、次のようなものではありませんでしたか？（例えば `day.count.count` でアクセスしようとすると次のように出るはずです）

```
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'count')
```

これはいわゆる Javaでいう `NullPointerException` 、C# でいうところの `NullReferenceException` です。
カレンダーは、v-for で１日ごとに描画をおこなっていますよね。その中には、azain4645さんのキャプチャにあるとおり、countプロパティの存在しない日も存在しています。

その状況で「countプロパティ内のcountプロパティ」にアクセスしようとすると、「一つ目のcountプロパティ」が存在しないので、「存在しないオブジェクトの子要素にアクセスすることはできない」という理屈から上記エラーが出ます。

つまり、このエラーを解決する方法は「存在しないオブジェクトの子要素にアクセスしない」コードを書くことです。そのため、「一つ目のcountプロパティが存在するかどうか」をチェックした上で「二つ目のcountプロパティ」にアクセスすべきなのですが、TypeScriptにはオプショナルチェーンという便利な機能があるので、今回はそれを活用するコードを例示しますね。

```vue
      <div 
        v-for="(day, index) in week" 
        :key="index"
        style="flex:1;min-height:100px;"
        :class="`${ 
          currentMonth != day.month ? 'bg-gray-100' : ''
        } border-r border-b border-gray-300 border-solid text-center`"
      >
        {{ day.date }}
        {{ day.count?.count }}

      </div>
```

このように `day.count?.count` のような書き方（オプショナルチェーン）を使えば「day.countが存在するなら day.count.count にアクセスする」ようにできます。

また、 `day.count?.count` が undefinedを返す（つまり day.count か day.count.count のどちらかが存在しない）時に 0 を表示したいということであれば、次のようにもかけます。

```vue
{{ day.count?.count ?? 0 }}
```

どちらの記法もTypeScriptではよく使うので、よければ使ってみてください！

**Comment by azain4645** [comment]
すみません。よく考えたらそうなりますね^^;
 
day.count?.count
で表示できました。（変数名がイマイチなのは後で見直します笑）
ありがとうございます
