### ISSUE TITLE
PropsとEmitについて

### ISSUE THREAD

**Issue by azain4645** [azain4645/thanksHabit#4]
https://github.com/azain4645/thanksHabit/blob/208fd89ff12fd26478393118ecd15e9bfa40d6da/components/modal.vue#L2-L8

モーダルのコンポーネントを自作している最中です。
親の方でモーダルを表示するかの状態と、開く・閉じるのメソッドをもっており、
子には、状態をpropsで渡し、閉じるのみ子から実行できるようにemitで持たせようと
していますが、うまくいきません。

あまり、defineEmitsを用いる実装が公式含めてあまりよくわからなかったのですが、使い方についてまとまっている記事とかありませんか？

**Comment by azain4645** [comment]
```
<script setup>
  const showContent = ref(true)

  const openModal = () => showContent.value = true
  const closeModal = () => showContent.value = false
</script>

<template>
  <button v-on:click="openModal" >Click</button>

  <modal 
    show-content="showContent"
    @onClick="closeModal"  
  /> 
</template>
```
親側はこんな感じです

**Comment by gel1123** [comment]
@azain4645 
お疲れ様です！ defineEmitsだけで調べると、「emitsの使い方を知っている前提」のドキュメントが多くて分かりにくいですよね！

見たところ、下記の記事だと「emitsの定義の仕方」と「発行したemitを親コンポーネントで拾うコード」の双方を書くことができているので、そちらご覧いただけると理解が捗ると思います！

https://programmer-note.hatenablog.com/entry/2021/11/28/171111

（もし理解が難しければ気軽に申し付けください！ propsの方ももし分からなければご質問お送りください）

-------

PropsやEmitsの使い方とはちょっと外れますが、上記で記載くださってるコードに記法誤り（だったはず）のものを見つけたので、連携しますね！

具体的には、ここです。

```diff
  <modal 
    show-content="showContent"
-    @onClick="closeModal"  
+    @click="closeModal"   
  /> 
```

Vueにおいて「v-on」は「@」で略して書けるのですが、「v-on:click」は「@onClick」ではなく「@click」と書くのが正しいです。

（とはいえどちらにせよここは、おそらく azainさんの意図としてはきっと `@closeModal` としたいのかな？　と思っています。Emitsの使い方について、前述の解説記事読んだ上でちょっとこの辺り見直してみてください！）

**Comment by azain4645** [comment]
ありがとうございます。一応props,emit,slotを使って動作自体はできました！

ただ、実装してみて気になるのが、openやclose、表示の状態は親が持っていることに違和感を感じています。
複数のページで使う場合に、状態とメソッドを親がそれぞれ宣言するのは面倒なような気がして。。
コンポーネントとして、そのあたりはどう考えるのが良いでしょうか？

**Comment by azain4645** [comment]
```
<script setup>
  const showContent = ref(true)

  const openModal = () => showContent.value = true
  const closeModal = () => showContent.value = false
</script>

<template>
  <button v-on:click="openModal" >Click</button>

  <modal 
    :show-content="showContent"
    @closeModal="closeModal"  
  >
    これはテストコンポーネント
  </modal>
</template>
```
親のコードがこんな感じです

**Comment by gel1123** [comment]
@azain4645 
おはようございます！　お待たせしました、コード見てみました。
良い感じですね！

> ただ、実装してみて気になるのが、openやclose、表示の状態は親が持っていることに違和感を感じています。
> 複数のページで使う場合に、状態とメソッドを親がそれぞれ宣言するのは面倒なような気がして。。
> コンポーネントとして、そのあたりはどう考えるのが良いでしょうか？

私はこの点については、問題ないと考える性質です。
というのも、私はモーダルをこのようなものと捉えているからです。

* モーダルコンポーネントは、あくまでも「モーダルを提供するだけの道具」
* 「モーダル（道具）をいつどのように使うか」は使う側（つまり親）の都合によるので、親がモーダルの状態を管理するのは正しい

扱いやすさ的にも、この方が例えば
* 「１ページ中に初期表示時のローディングモーダル」と、
* 「特定の操作をしたときに表示する別のモーダルがある」ような時に、

親の都合で表示状態をすぐにいじくることができて便利だなと感じます（算出プロパティで既存のrefを元にモーダル表示状態を生成することが出来るのも良いところかなと）

一方で、もし「モーダルが状態をもつ」方式をするとしたら、
* 「モーダルが状態をもつ」
* 「モーダルは操作のみを公開する」
* 「公開された操作をpropsやprovide経由などで、モーダルを使うコンポーネント（子）に渡す」

という流れになります。

そうなると
* 「モーダルはアプリケーションの中でほぼ最上位の階層（app.vueなど）に１つだけ存在する」
* 「操作をprops or provide で提供する」

という性質上、これはいわゆる「モーダル === グローバルな存在」として扱わないといけなくなります。

> ※ モーダルをグローバルな存在とせず、都度「使いたいコンポーネントの直近の親」などにするケースも考えられますが、可読性からあまり採用しないケースが多いかな？と考えて割愛しています

アプリケーションの規模が小さいうちはこれでもさほど、使い勝手に問題はないのですが、
次第にアプリケーションの規模が大きくなり、コンポーネントが数・階層ともに増えてくると、
「アプリケーションにおけるグローバルな存在」は相対的に見えづらくなり、
使うのが困難になっていきがちです。

ですので、その状況を回避するために、個人的には「モーダルが状態をもつ（モーダルが祖先でありグローバルになりがち）」より「モーダルは状態を持たない（モーダルは子であり都度宣言する）」スタイルの方が好きですね！

**Comment by azain4645** [comment]
確かに複数のモーダル使いたい場合にもこの方が良さそうですね。
ありがとうございます！基本的にはこの感じで進めてみます
