### ISSUE TITLE
カレンダーでモーダルを利用

### ISSUE THREAD

**Issue by azain4645** [azain4645/thanksHabit#5]
モーダルの考え方について、ありがとうございました。
とりあえず、簡単にカレンダーにモーダルを追加しました。

https://github.com/azain4645/thanksHabit/blob/344bd3e188bdb7fae1c914701001abff915c1594/pages/calender.vue#L4-L13

slotの中身を動的に書き換えたいのですが、slotの中身をrefにしてopenModalするときに、refしている値を書き換えるようにしました。
このような考え方で合っていますか？

**Comment by gel1123** [comment]
@azain4645 
お疲れ様です！　コード見ました。今回の場合はこれであってますよ！

このほかのパターンを挙げるとしたら、例えば「カレンダーを日毎にコンポーネントとして持たせて、refを使わず直接 v-forから渡された `day.count?.count` をモーダル内のコンテンツとして埋め込んでやる方法が考えられます。
