### ISSUE TITLE
カレンダーでカウントを表示したい

### ISSUE THREAD

**Issue by azain4645** [azain4645/thanksHabit#7]
https://github.com/azain4645/thanksHabit/blob/63b4ed8a0e2608c216f70028cd052d7815f2197d/pages/calender.vue#L77-L83

firestoreに日付ごとのサブコレクションでデータを保存できるようになったので、カレンダーの方でも集計した値を表示させたいです。
NoSQLでは集計関数がないとのことなので、工夫が必要そうですが、どうされていますか？

**Comment by gel1123** [comment]
@azain4645 
おはようございます！　そうですね、集計関数のようなクエリ時にまとめて計算してくれるものはないので、ここは力技で行きます！　地道に、必要な値をフロントエンドで自ら合算していくしかないですね（工夫ゼロの回答ですみません...笑）

**Comment by gel1123** [comment]
@azain4645 
お待たせしました！　実際にどのようにコードを修正すればいいか、をここに書くにはあまりに長くなるので、
[上記のプルリク](https://github.com/azain4645/thanksHabit/pull/8)で動くようになるコードお送りします！

動かしながらコード見てみてください。

#### 補足1
もしもJavaScriptの非同期関数まわり（async, await）あまりご存じでなければ、一度Web上の記事などから学習してみてください！（ご存じでしたらすみません）

React、Vueともにバックエンドとの通信が絡み始めると、非同期関数を使うべき場面は頻繁に登場しますので、このあたりしっかり理解された方がコード実装しやすくなるはずです！

（JavaScriptではPromiseという非同期的に扱えるオブジェクトがあるのですが、Promiseを都度そのまま扱うのは、いわゆる「コールバック地獄」を引き起こして可読性が悪くなってしまうので、極力 async, await を使うのが良いです）

#### 補足2
Promise.all() は非同期処理をまとめるのに便利なので、割と使う機会が多いです！
よくあるのが `何らかの配列.map(async (data) => 返却値)` が返した Promise配列を、ひとまとめに「このPromiseが並列的に実行されて全部解決されるまで待つ」ときに使うケースです。今回の修正コードでも、これを利用しています。
